blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('showresult/', views.search_results, name='search_results'),
    
    
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blogapp')),
]

blogapp/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.

# Create a custom manager to retriev all posts that have a PUBLISHED status.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return(super().get_queryset().filter(status=Post.Status.PUBLISHED))



class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blogapp_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    
    objects = models.Manager()
    published = PublishedManager()
    
    class Meta:
        ordering = ['-publish']
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blogapp:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blogapp/forms.py
# Creating forms from models
from django import forms
from .models import Comment



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blogapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .forms import CommentForm
from .models import Post, Comment
from django.db.models import Q
# Create your views here.

def post_list(request):
    post_list = Post.published.all()
    # pagination with limited posts per page
    paginator = Paginator(post_list, 2)
    page_number = request.GET.get('page', 1)
    posts = paginator.page(page_number)
    return render(request, 'blogapp/post/list.html', {'posts':posts})


def search_results(request):
    query = request.GET.get('q')
    posts = Post.published.all()
    if query:
        posts = posts.filter(Q(title__icontains=query)|Q(body__icontains=query))
    
    return render(request, 'blogapp/post/showsearch.html', {'posts':posts, 'query':query})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, slug=post, publish__year=year, publish__month=month, publish__day=day)
    
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect('blogapp:post_detail', year=year, month=month, day=day, post=post.slug)
    else:
        form = CommentForm()
    return render(request, 'blogapp/post/detail.html', {'post':post, 'comments':comments, 'form':form})


 

blogapp/templates/blogapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blogapp:post_list' %}">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'blogapp:post_list' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page header with logo and tagline-->
    {% block header %}

    {% endblock %}
    <div class="container mt-3">

        <div class="row">
            <!-- Blog entries-->
            <div class="col-lg-8">
                {% block content %}

                {% endblock %}

            </div>
            <!-- Side widgets-->
            <div class="col-lg-4">
                <!-- Search widget-->
                <div class="card mb-4">
                    <div class="card-header">Search</div>
                    <div class="card-body">
                        <div class="input-group">
                            <form method="get" action="{% url 'blogapp:search_results' %}">
                                <input class="form-control" type="text" name="q" placeholder="Search posts..."
                                    value="{{ query|default:'' }}" aria-label="Enter search term..."
                                    aria-describedby="button-search" />
                                <button class="btn btn-primary mt-3" id="button-search" type="submit">Search</button>
                            </form>

                        </div>
                    </div>
                </div>
                <!-- Categories widget-->
                <div class="card mb-4">
                    <div class="card-header">Categories</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">Web Design</a></li>
                                    <li><a href="#!">HTML</a></li>
                                    <li><a href="#!">Freebies</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">JavaScript</a></li>
                                    <li><a href="#!">CSS</a></li>
                                    <li><a href="#!">Tutorials</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Side widget-->
                <div class="card mb-4">
                    <div class="card-header">Side Widget</div>
                    <div class="card-body">You can put anything you want inside of these side widgets. They are easy to
                        use, and feature the Bootstrap 5 card component!</div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js'%}"></script>
</body>

</html>

blogapp/templates/blogapp/post/comment.html
<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
            {% include 'blogapp/post/comment_form.html' %}
            <!-- Comment with nested comments-->
            <div class="d-flex mb-4">
                <!-- Parent comment-->
                <div class="flex-shrink-0"><img class="rounded-circle"
                        src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    If you're going to lead a space frontier, it has to be government; it'll never be
                    private enterprise. Because the space frontier is dangerous, and it's expensive, and it
                    has unquantified risks.
                    <!-- Child comment 1-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle"
                                src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            And under those conditions, you cannot establish a capital-market evaluation of
                            that enterprise. You can't get investors.
                        </div>
                    </div>
                    <!-- Child comment 2-->
                    <div class="d-flex mt-4">
                        <div class="flex-shrink-0"><img class="rounded-circle"
                                src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            When you put money directly to a problem, it makes a good headline.
                        </div>
                    </div>
                </div>
            </div>
            <!-- Single comment-->
            <div class="d-flex">
                <div class="flex-shrink-0"><img class="rounded-circle"
                        src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                <div class="ms-3">
                    <div class="fw-bold">Commenter Name</div>
                    When I look at the universe and all the ways the universe wants to kill us, I find it
                    hard to reconcile that with statements of beneficence.
                </div>
            </div>
        </div>
    </div>
</section>

blogapp/templates/blogapp/post/detail.html
{% extends 'blogapp/base.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}

{% block content %}
<!-- Nested row for non-featured blog posts-->
<div class="container mt-3">
    <div class="row">
        <div class="col-lg-12">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{post.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on {{post.publish|date:"Y, M, d"}} by
                        {{post.author|title}}</div>
                    <!-- Post categories-->
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded"
                        src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{post.body|linebreaks}}</p>

                </section>
            </article>
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        <!-- Comment form-->
                        <form class="mb-4" method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit">Post Comment</button>
                        </form>
                        <!-- Comment with nested comments-->
                        <div class="d-flex mb-4">
                            <!-- Parent comment-->
                            <div class="flex-shrink-0"><img class="rounded-circle"
                                    src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">

                                <div class="fw-bold">Commenter Name</div>
                                If you're going to lead a space frontier, it has to be government; it'll never be
                                private enterprise. Because the space frontier is dangerous, and it's expensive, and it
                                has unquantified risks.
                                <!-- Child comment 1-->
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0"><img class="rounded-circle"
                                            src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        And under those conditions, you cannot establish a capital-market evaluation of
                                        that enterprise. You can't get investors.
                                    </div>
                                </div>
                                <!-- Child comment 2-->
                                <div class="d-flex mt-4">
                                    <div class="flex-shrink-0"><img class="rounded-circle"
                                            src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When you put money directly to a problem, it makes a good headline.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Single comment-->
                        {%for comment in comments%}
                        <div class="d-flex mb-3">
                            <div class="flex-shrink-0"><img class="rounded-circle"
                                    src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold"> {{comment.name}} </div>
                                {{comment.body}}
                            </div>
                        </div>
                        {% empty %}
                        <div class="d-flex mb-3">
                            <div class="flex-shrink-0"><img class="rounded-circle"
                                    src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold"> No Comments yet. </div>

                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>

    </div>
</div>

{% endblock %}

blogapp/templates/blogapp/post/list.html
{% extends 'blogapp/base.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}
{% block header %}
<header class="py-5 bg-light border-bottom mb-4">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Welcome to Blog Home!</h1>
            <p class="lead mb-0">A Bootstrap 5 starter layout for your next blog homepage</p>
        </div>
    </div>
</header>
{% endblock %}
{% block content %}
<!-- Nested row for non-featured blog posts-->
<div class="row">
    {% for post in posts %}
    <div class="col-lg-6">

        <!-- Blog post-->
        <div class="card mb-4">
            <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg"
                    alt="..." /></a>
            <div class="card-body">
                <div class="small text-muted">{{post.publish}} by {{post.author}}</div>
                <h2 class="card-title h4">{{post.title}}</h2>
                <p class="card-text">{{post.body|truncatewords:30|linebreaks}}</p>
                <a class="btn btn-primary" href="{{post.get_absolute_url}}">Read more →</a>
            </div>
        </div>

    </div>
    {% endfor %}

</div>



{% include 'blogapp/post/pagination.html' with page=posts %}
{% endblock %}

blogapp/templates/blogapp/post/pagination.html
<!-- Pagination-->
<nav aria-label="Pagination">
    <hr class="my-0" />
    <ul class="pagination justify-content-center my-4">
        <!-- Previous Page Link -->
        <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
            {% if page.has_previous %}
                <a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
            {% else %}
                <span class="page-link">Previous</span>
            {% endif %}
        </li>

        <!-- Page Numbers -->
        {% for num in page.paginator.page_range %}
            <li class="page-item {% if page.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endfor %}

        <!-- Next Page Link -->
        <li class="page-item {% if not page.has_next %}disabled{% endif %}">
            {% if page.has_next %}
                <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
            {% else %}
                <span class="page-link">Next</span>
            {% endif %}
        </li>
    </ul>
</nav>

blogapp/templates/blogapp/post/showsearch.html
{% extends 'blogapp/base.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}
<!--  -->
{% block content %}
<!-- Nested row for non-featured blog posts-->
<div class="row">
    {% if query %}
    <h2>
        Search Result for : "{{query}}"
    </h2>
    {% endif %}
    {% for post in posts %}
    <div class="col-lg-6">

        <!-- Blog post-->
        <div class="card mb-4">
            <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg"
                    alt="..." /></a>
            <div class="card-body">
                <div class="small text-muted">{{post.publish}} by {{post.author}}</div>
                <h2 class="card-title h4">{{post.title}}</h2>
                <p class="card-text">{{post.body|truncatewords:30|linebreaks}}</p>
                <a class="btn btn-primary" href="{{post.get_absolute_url}}">Read more →</a>
            </div>
        </div>

    </div>
    {% empty %}
    <p>No posts found matching your search query.</p>
    {% endfor %}

</div>



{% endblock %}